### ISSUE TITLE
Is using the nthreads parameter safe?

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/n5-blosc#1]
In https://github.com/zarr-developers/zarr-python/pull/496 @chris-allan raised the following concern that we should investigate

> `JBlosc.set_nthreads()` is going to manipulate the c-blosc threadpool via `blosc_set_nthreads()` in C. Semantically equivalent to `numcodec.blosc.set_nthreads()` in Zarr on the Python side. That thread pool is global. Under the hood of `BloscCompression` it seems like `JBlosc.decompressCtx()` is being used. If we delve down into context based compression in c-blosc each context execution of `parallel_blosc()` just ends up running `blosc_set_nthreads()` anyway. Thus, it doesn't seem like it would make much sense to be on each Compression  instance. At worst there's the possibility of data loss; Blosc is  re-initialized if the thread counts change. I'd have to read more of  c-blosc to be completely certain of the semantics.[...]

**Comment by chris-allan** [comment]
I've followed up on this by digging into the c-blosc code path that JBlosc uses. Specifically, the 
`blosc_compress_ctx()` and `blosc_decompress_ctx()` C functions that n5-blosc ends up calling when invoking `JBlosc.compressCtx()` and `JBlosc.decompressCtx()`.

My previous statement is wrong. During each context execution `blosc_set_nthreads_()` (note the trailing underscore) **not** `blosc_set_nthreads()` is called. This results in a context specific thread pool being created, if required, that is both thread safe and concurrent. These semantics can be loosely inferred by reading the header documentation for `blosc_compress_ctx()`:

 * https://github.com/Blosc/c-blosc/blob/v1.14.2/blosc/blosc.h#L274

Thus, I think the current API makes complete sense; it is not dangerous. The only weird thing at the moment that I can think of related to this is how friendly the current behavior actually is. When writing I can't think of an improvement over the current API:

```java
N5Writer n5 = new N5FSWriter("test.n5");
DataType dataType = DataType.UINT16;
Compression compression = new BloscCompression(
    "lz4",
    5,  // clevel
    BloscCompression.SHUFFLE,  // shuffle
    0,  // blocksize (0 = auto)
    1  // nthreads
);
n5.createDataset(
    "/0",
    new long[] { sizeX, sizeY, sizeC },
    new int[] { tileWidth, tileHeight, 1 },
    dataType, compression
);
...
```

However, if you want to control the number of threads used during decompression, if for example you have quite a large chunk size, you cannot really do so safely. You have to guess the parameters other than `nthreads` as `cname`, `clevel`, `shuffle`, and `blocksize` are all private member variables. Would it make sense to change the scope to `public final` so that at the very least you could create a new instance with an updated `nthreads`?

All of the above is based on reviewing c-blosc at the `v1.14.2` tag which is the closest point to the `blosc1` package version of `1.14.2+ds1-1` currently available as part of Ubuntu 18.04 LTS.

**Comment by axtimwalde** [comment]
Thanks for investigating.  I agree that it makes sense to let users modify the number of threads more conveniently.  I think that making `nthreads` non-final and adding a getter and setter would be the cleanest solution.  I do not think that the other parameters need to be exposed the same way.  Will do this later today or tomorrow.

**Comment by chris-allan** [comment]
Sounds like a plan to me. I guess the only question is whether the other Blosc properties should also be accessible. Maybe just via getters?

Happy to do the work on this one and open a PR if you have other things on the go.

**Comment by axtimwalde** [comment]
Thanks @chris-allan for investigating and sorry for letting this sit.
