### ISSUE TITLE
Ship with Fiji

### ISSUE THREAD

**Issue by tischi** [saalfeldlab/n5-blosc#2]
Hi @axtimwalde,

1. Do you think this is significantly better than the other compression algorithms?
1. Are there any plans to ship this with Fiji, including the necessary binaries for all operating systems?

cc @constantinpape

**Comment by constantinpape** [comment]
>     1. Do you think this is significantly better than the other compression algorithms?

I did benchmarks for this at some point. If I remember correctly, blosc with lz4 compression and shuffle filter was a significantly faster in compression speed, the size of compressed chunks was a bit smaller (maybe 10%) and decompression was a bit faster (maybe also 10%).

I will try to redo this for the data we are working with right now soon, so we have a clear data point on this.

@axtimwalde 
So far I have only implemented blosc compression for zarr. How exactly does n5 serialize the blosc compression options to the `compression` fileld in the dataset `attributes.json`?

**Comment by axtimwalde** [comment]
@tischi Happy to have this included in Fiji, but somebody has to do the legwork to distribute (possibly redundantly) libblosc for all supported platforms, I do not currently have the resources to do this.  Anybody getting funded to maintain Fiji?

I personally only use this to support all of Zarr through the n5-zarr bindings.  But since compressors are runtime extensions to n5, this will also work without it, just cannot do blosc then.

@cpape like this https://github.com/saalfeldlab/n5-blosc/blob/master/src/main/java/org/janelia/saalfeldlab/n5/blosc/BloscCompression.java#L55-L68
That is the beauty of my API and makes it so easy to add other compressors without touching central registries :).  Thanks to scijava, GSON, and Java annotations.

**Comment by axtimwalde** [comment]
Actually it would be really nice to include this in the Fiji distribution, including n5-zarr. I will sniff around for help...

**Comment by tischi** [comment]
> Anybody getting funded to maintain Fiji?

Maybe @fjug :-) Do you have some Fiji dev-ops (wo)man-power to offer to help out? 

> ...somebody has to do the legwork to distribute (possibly redundantly) libblosc for all supported platforms

I think @joshmoore might also be interested or know something?!

**Comment by joshmoore** [comment]
@tischi : certainly the solution would work similarly to the one we discussed for wrapping libhdf5 in the Java ecosystem.

**Comment by constantinpape** [comment]
> @cpape like this https://github.com/saalfeldlab/n5-blosc/blob/master/src/main/java/org/janelia/saalfeldlab/n5/blosc/BloscCompression.java#L55-L68
> That is the beauty of my API and makes it so easy to add other compressors without touching central registries :). Thanks to scijava, GSON, and Java annotations.

That's indeed very neat. Just so I understand it correctly, in the `attributes.json` it would look like this:
```json
{"compression": {"cname": "blosclz", "clevel": 6, "shuffle": 0, "blocksize": 0, "nthreads": 1}}
```
Correct?
Also, two follow up questions:
Which values are supported for `"cname"`? Also, is it necessary to  have the fields `"blocksize"` and `"nthreads"` (I think these are not necessary in zarr)?

**Comment by axtimwalde** [comment]
https://github.com/Blosc/c-blosc/blob/master/blosc/blosc.h#L73-L79

no, they default to 0 and 0 (which means 1)

**Comment by axtimwalde** [comment]
n5-blosc is now shipping with support for Linux64, MacOS, and Win64 with the N5 update site.
